### ISSUE TITLE
TwitCasting Download Question

### ISSUE THREAD

**Issue by Veshurik** [kassarin/Wondershard#1]
Hello! Project about TwitCasting Download now closed, but I don't know how contact the author, so I decided to ask here.

Is it possible somehow to download password-protected videos like [this](https://twitcasting.tv/duca_0406/movie/736550040) and [this](https://twitcasting.tv/duca_0406/movie/736547964)?

These TwitCasting usual download services on Google doesn't work at all with common videos (or only for money), that's so strange... Thanks!

**Comment by kassarin** [comment]
Sorry I'm only using whatever [@niseyami](https://github.com/niseyami) provided to make the batch file, you'll have to seek support from them directly.
